const translations = {
    ru: {
        nav_home: "Главная",
        nav_catalog: "Каталог",
        nav_about: "О производстве",
        nav_contacts: "Контакты",
        nav_order: "Заказать образец",
        hero_h1: "Основа,<br><em>на которую можно рассчитывать</em>",
        hero_p: "Стеклянная мозаика, созданная выдерживать любые нагрузки. Она абсолютно не боится жара, сурового холода и резких перепадов температур, сохраняя свой безупречный вид на долгие годы.",
        hero_btn_catalog: "Смотреть каталог",
        hero_btn_pdf: "Скачать PDF",
        stat_colors: "Цветовых решений",
        stat_water: "Водопоглощение",
        stat_frost: "Циклов морозостойкости",
        feat_1_title: "Водонепроницаемость",
        feat_1_desc: "Коэффициент водопоглощения меньше 0.1%. Идеально для бассейнов и хамамов.",
        feat_2_title: "Морозостойкость",
        feat_2_desc: "Выдерживает не менее 100 циклов перехода от минусовых к плюсовым температурам до -30°C.",
        feat_3_title: "Жаропрочность",
        feat_3_desc: "Устойчива к перепадам в диапазоне от +15 до +150°C. Подходит для облицовки каминов.",
        feat_4_title: "Устойчивость",
        feat_4_desc: "Цвета не выгорают под воздействием ультрафиолета. Стойкость к агрессивным химическим веществам.",
        cat_title: "Коллекция мозаики",
        cat_desc: "Выберите идеальную мозаику по размеру и форме чипа",
        filter_all: "Все",
        filter_glass: "Стеклянная",
        filter_honeycomb: "Соты",
        filter_textured: "Рефленная",
        filter_other: "Другое",
        about_title: "О производстве",
        about_p1_html: "ООО «GOOD GLASS MOSAIC» — производитель мозаичной плитки из стекла, располагающийся в Ташкентской области. Также наша продукция под брендом <strong>PREMIUM MOSAIC</strong> представлена:<br>\n                    <a href=\"https://yandex.ru/maps/?pt=69.246214,41.355954&z=17\" target=\"_blank\" style=\"text-decoration: underline; color: inherit;\">в нашем фирменном магазине в Ташкенте на строительном рынке Жами (номер магазина 2-20)</a>.",
        about_p2: "Несмотря на то, что мозаика сделана из стекла, она гораздо прочнее, чем обычное стекло. Это обусловлено тем, что она проходит через печь с высокой температурой.",
        about_p3: "По желанию заказчика, мы можем миксовать цвета и разнообразные оттенки, тем самым воплощая в реальность самые смелые и неординарные дизайнерские идеи.",
        footer_contact_title: "Контакты",
        footer_address: "Ташкентская область, Юкори Чирчикский район, Миям Кангли МФЙ, ул. Калдиргоч, дом 4",
        footer_copy: "&copy; 2026 Premium Mosaic. Все права защищены.",
        modal_title: "Связаться с нами",
        modal_phone: "Позвонить по телефону",
        modal_tg: "Написать в Telegram",
        modal_wa: "Написать в WhatsApp",
        cat_name_1x1: 'Серия 1x1 см',
        cat_name_2x2: 'Серия 2x2 / 2.5x2.5 см',
        cat_name_4x4: 'Серия 4x4 см',
        cat_name_glass: 'Стеклянная мозаика',
        cat_name_honeycomb: 'Соты',
        cat_name_drop: 'Drop',
        cat_name_textured: 'Рефленная',
        cat_name_other: 'Эксклюзив'
    },
    uz: {
        nav_home: "Bosh sahifa",
        nav_catalog: "Katalog",
        nav_about: "Ishlab chiqarish",
        nav_contacts: "Kontaktlar",
        nav_order: "Namuna buyurtma qilish",
        hero_h1: "Tayanishingiz mumkin<br><em>bo'lgan asos.</em>",
        hero_p: "Har qanday yuklamalarga bardosh berish uchun yaratilgan shisha mozaika. U jazirama issiqdan, qattiq sovuqdan va keskin harorat o'zgarishlaridan umuman qo'rqmaydi va uzoq yillar davomida o'zining mukammal ko'rinishini saqlab qoladi.",
        hero_btn_catalog: "Katalogni ko'rish",
        hero_btn_pdf: "PDF yuklab olish",
        stat_colors: "Rang yechimlari",
        stat_water: "Suv singdirish",
        stat_frost: "Muzga chidamlilik davrlari",
        feat_1_title: "Suvga chidamlilik",
        feat_1_desc: "Suv singdirish koeffitsienti 0.1% dan kam. Hovuzlar va hamamlar uchun ideal.",
        feat_2_title: "Muzga chidamlilik",
        feat_2_desc: "Manfiy haroratdan musbat haroratgacha bo'lgan -30°C gacha kamida 100 ta davrga bardosh beradi.",
        feat_3_title: "Issiqlikka chidamlilik",
        feat_3_desc: "+15 dan +150°C gacha bo'lgan harorat o'zgarishlariga chidamli. Kaminlarni qoplash uchun mos keladi.",
        feat_4_title: "Turg'unlik",
        feat_4_desc: "Ranglar ultrabinafsha nurlari ostida so'nmaydi. Agressiv kimyoviy moddalarga chidamli.",
        cat_title: "Mozaika to'plami",
        cat_desc: "Chipning o'lchami va shakli bo'yicha mukammal mozaikani tanlang",
        filter_all: "Barchasi",
        filter_glass: "Shisha",
        filter_honeycomb: "Asalari uyasi",
        filter_textured: "Relyefli",
        filter_other: "Boshqa",
        about_title: "Ishlab chiqarish haqida",
        about_p1_html: "«GOOD GLASS MOSAIC» MChJ — Toshkent viloyatida joylashgan shisha mozaika ishlab chiqaruvchi korxona. Shuningdek, mahsulotimiz <strong>PREMIUM MOSAIC</strong> brendi ostida:<br>\n                    <a href=\"https://yandex.ru/maps/?pt=69.246214,41.355954&z=17\" target=\"_blank\" style=\"text-decoration: underline; color: inherit;\">Toshkent shahridagi Jomiy qurilish bozorida (do'kon raqami 2-20) joylashgan firma do'konimizda taqdim etilgan</a>.",
        about_p2: "Mozaika shishadan yasalgan bo'lsa-da, oddiy shishadan ancha kuchliroqdir. Bu uning yuqori haroratli pechdan o'tishi bilan bog'liq.",
        about_p3: "Mijozning xohishiga ko'ra, biz turli xil ranglar va soyalarni aralashtirishimiz mumkin, shu bilan eng jasur va g'ayrioddiy dizayn g'oyalarini haqiqatga aylantiramiz.",
        footer_contact_title: "Kontaktlar",
        footer_address: "Toshkent viloyati, Yuqori Chirchiq tumani, Miyam Qangli MFY, Qaldirg'och ko'chasi, 4-uy",
        footer_copy: "&copy; 2026 Premium Mosaic. Barcha huquqlar himoyalangan.",
        modal_title: "Biz bilan bog'lanish",
        modal_phone: "Qo'ng'iroq qilish",
        modal_tg: "Telegramda yozish",
        modal_wa: "WhatsAppda yozish",
        cat_name_1x1: '1x1 sm seriyasi',
        cat_name_2x2: '2x2 / 2.5x2.5 sm seriyasi',
        cat_name_4x4: '4x4 sm seriyasi',
        cat_name_glass: 'Shisha mozaika',
        cat_name_honeycomb: 'Asalari uyasi',
        cat_name_drop: 'Drop',
        cat_name_textured: 'Relyefli',
        cat_name_other: 'Eksklyuziv'
    }
};

let currentLang = 'ru';
